# Generated by Django 5.2.17 on 2026-09-14 09:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='class_day',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='timing',
        ),
        migrations.AddField(
            model_name='batch',
            name='class_days',
            field=models.CharField(default='Monday, Tuesday, Wednesday, Thursday, Friday', help_text='Days on which class is conducted (e.g. Monday, Wednesday, Friday or Saturday)', max_length=255),
        ),
        migrations.AddField(
            model_name='batch',
            name='end_time',
            field=models.TimeField(default=datetime.time(13, 0), help_text='Class ending time'),
        ),
        migrations.AddField(
            model_name='batch',
            name='start_time',
            field=models.TimeField(default=datetime.time(9, 30), help_text='Class starting time'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='schedule_type',
            field=models.CharField(choices=[('DAILY', 'Daily Class'), ('WEEKLY', 'Weekly Class')], default='DAILY', max_length=20),
        ),
    ]
