# Generated by Django 5.2.17 on 2026-09-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator_app', '0002_remove_batch_class_day_remove_batch_timing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyevaluation',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='dailyevaluation',
            name='improvements',
        ),
        migrations.RemoveField(
            model_name='dailyevaluation',
            name='strengths',
        ),
        migrations.RemoveField(
            model_name='dailyevaluation',
            name='task_completion_score',
        ),
        migrations.RemoveField(
            model_name='dailyevaluation',
            name='technical_score',
        ),
        migrations.AddField(
            model_name='dailyevaluation',
            name='areas_for_improvement',
            field=models.TextField(blank=True, help_text='Areas needing improvement'),
        ),
        migrations.AddField(
            model_name='dailyevaluation',
            name='attendance_percentage',
            field=models.FloatField(default=0.0, help_text='Current attendance % at evaluation time'),
        ),
        migrations.AddField(
            model_name='dailyevaluation',
            name='classmate_interaction_score',
            field=models.FloatField(default=80.0, help_text='Interaction with classmates & teamwork'),
        ),
        migrations.AddField(
            model_name='dailyevaluation',
            name='doubt_clearing_score',
            field=models.FloatField(default=75.0, help_text='Asking doubts & clearing them'),
        ),
        migrations.AddField(
            model_name='dailyevaluation',
            name='general_remarks',
            field=models.TextField(blank=True, help_text='General feedback and mentor advice'),
        ),
        migrations.AddField(
            model_name='dailyevaluation',
            name='interested_areas',
            field=models.TextField(blank=True, help_text='Interested areas / career focus (e.g. Backend, Frontend, Cloud)'),
        ),
        migrations.AddField(
            model_name='dailyevaluation',
            name='ppt_evaluation_score',
            field=models.FloatField(default=75.0, help_text='PPT / PDF evaluation (slides, images, clarity)'),
        ),
        migrations.AddField(
            model_name='dailyevaluation',
            name='ppt_explanation_notes',
            field=models.CharField(blank=True, help_text='Quality of explanations in slides', max_length=255),
        ),
        migrations.AddField(
            model_name='dailyevaluation',
            name='ppt_has_images',
            field=models.BooleanField(default=True, help_text='Images/diagrams/screenshots included'),
        ),
        migrations.AddField(
            model_name='dailyevaluation',
            name='ppt_slide_count',
            field=models.IntegerField(blank=True, default=6, help_text='Number of slides/pages', null=True),
        ),
        migrations.AddField(
            model_name='dailyevaluation',
            name='presentation_score',
            field=models.FloatField(default=75.0, help_text='Presentation skill & way of presenting'),
        ),
        migrations.AddField(
            model_name='dailyevaluation',
            name='strongest_areas',
            field=models.TextField(blank=True, help_text='Strongest area of the student'),
        ),
        migrations.AddField(
            model_name='dailyevaluation',
            name='suggestion_implementation_score',
            field=models.FloatField(default=80.0, help_text='Taking suggestions & implementing them'),
        ),
        migrations.AddField(
            model_name='dailyevaluation',
            name='tasks_completed',
            field=models.IntegerField(default=5, help_text='Tasks completed by student today'),
        ),
        migrations.AddField(
            model_name='dailyevaluation',
            name='tasks_given',
            field=models.IntegerField(default=5, help_text='Total tasks/assignments given today'),
        ),
        migrations.AddField(
            model_name='dailyevaluation',
            name='tendency_to_study_score',
            field=models.FloatField(default=80.0, help_text='Tendency to study, curiosity & diligence'),
        ),
        migrations.AddField(
            model_name='dailyevaluation',
            name='tutor_interaction_score',
            field=models.FloatField(default=80.0, help_text='Interaction with tutor (responsiveness & engagement)'),
        ),
        migrations.AlterField(
            model_name='dailyevaluation',
            name='communication_score',
            field=models.FloatField(default=75.0, help_text='Communication & articulation'),
        ),
        migrations.AlterField(
            model_name='dailyevaluation',
            name='problem_solving_score',
            field=models.FloatField(default=75.0, help_text='Understanding problems & implementing solutions'),
        ),
        migrations.AlterField(
            model_name='dailyevaluation',
            name='punctuality_score',
            field=models.FloatField(default=80.0, help_text='Punctuality & session discipline'),
        ),
        migrations.AlterField(
            model_name='dailyevaluation',
            name='total_score',
            field=models.FloatField(default=0.0, help_text='Overall weighted score out of 100'),
        ),
    ]
