# Generated by Django 5.2.17 on 2026-09-14 11:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator_app', '0003_remove_dailyevaluation_feedback_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title or description of the task assigned', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed task instructions or requirements')),
                ('assigned_date', models.DateField(default=django.utils.timezone.now, help_text='The date that specific task is given')),
                ('due_date', models.DateField(blank=True, help_text='Expected completion deadline date', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='Date and time when the student completed the task', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('LATE', 'Completed Late'), ('OVERDUE', 'Overdue')], default='PENDING', max_length=20)),
                ('priority', models.CharField(choices=[('NORMAL', 'Normal'), ('HIGH', 'High Priority'), ('URGENT', 'Urgent')], default='NORMAL', max_length=20)),
                ('evaluator_remarks', models.CharField(blank=True, help_text='Remarks or feedback from evaluator', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_student_tasks', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_tasks', to='evaluator_app.batch')),
                ('daily_evaluation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_tasks', to='evaluator_app.dailyevaluation')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='evaluator_app.student')),
            ],
            options={
                'ordering': ['-assigned_date', '-created_at'],
            },
        ),
    ]
