# Generated by Django 5.2.17 on 2026-09-14 12:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator_app', '0004_studenttask'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Project title (e.g. E-Commerce Multi-Vendor Platform)', max_length=255)),
                ('project_type', models.CharField(choices=[('MAIN', 'Main / Capstone Project'), ('MINI', 'Mini Project'), ('ASSIGNMENT', 'Project Assignment'), ('PRACTICE', 'Practice Project'), ('CLIENT', 'Live / Client Project')], default='MAIN', max_length=30)),
                ('technologies', models.CharField(default='Python, Django, PostgreSQL, HTML5, CSS3, JavaScript', help_text='Technologies, frameworks, databases, and tools used (comma-separated)', max_length=500)),
                ('description', models.TextField(blank=True, help_text='Project objectives, features, system architecture & scope')),
                ('progress_percentage', models.IntegerField(default=0, help_text='Development progress from 0% to 100%')),
                ('status', models.CharField(choices=[('PLANNING', 'Planning & Design'), ('IN_PROGRESS', 'In Progress / Development'), ('UNDER_REVIEW', 'Under Evaluator Review'), ('COMPLETED', 'Completed'), ('ON_HOLD', 'On Hold / Needs Revision')], default='IN_PROGRESS', max_length=30)),
                ('start_date', models.DateField(default=django.utils.timezone.now, help_text='Project start / kick-off date')),
                ('target_completion_date', models.DateField(blank=True, help_text='Target delivery / deadline date', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='Timestamp when project was finalized / submitted', null=True)),
                ('github_repo_url', models.URLField(blank=True, help_text='GitHub or GitLab source repository URL')),
                ('live_demo_url', models.URLField(blank=True, help_text='Live deployed application URL (e.g. Render, Vercel, AWS)')),
                ('documentation_url', models.URLField(blank=True, help_text='Project documentation, presentation slides, or design link')),
                ('presentation_score', models.FloatField(default=0.0, help_text='Presentation & demo delivery score (0-100)')),
                ('code_quality_score', models.FloatField(default=0.0, help_text='Code quality, architecture & modularity score (0-100)')),
                ('ui_ux_score', models.FloatField(default=0.0, help_text='UI/UX design, responsiveness & aesthetic score (0-100)')),
                ('functionality_score', models.FloatField(default=0.0, help_text='Feature completeness & functionality score (0-100)')),
                ('viva_score', models.FloatField(default=0.0, help_text='Viva, Q&A and doubt clearing score (0-100)')),
                ('total_score', models.FloatField(default=0.0, help_text='Weighted overall evaluation score out of 100')),
                ('grade', models.CharField(blank=True, help_text='Grade: A+, A, B+, B, C, NI', max_length=10)),
                ('evaluator_feedback', models.TextField(blank=True, help_text='Comprehensive evaluator review & assessment comments')),
                ('strengths', models.TextField(blank=True, help_text='Key strengths observed in the project')),
                ('areas_to_improve', models.TextField(blank=True, help_text='Areas needing enhancement or refactoring')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='evaluator_app.batch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
                ('students', models.ManyToManyField(help_text='Select one or more students for individual or team projects', related_name='projects', to='evaluator_app.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_percentage', models.IntegerField(default=0)),
                ('status_at_update', models.CharField(blank=True, max_length=30)),
                ('notes', models.TextField(help_text='Milestone summary, changes made, blockers or evaluator remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_updates', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='evaluator_app.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
