# Generated by Django 5.2.17 on 2026-09-15 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator_app', '0005_project_projectupdate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttask',
            name='areas_for_improvement',
            field=models.TextField(blank=True, help_text='Areas needing improvement or revision'),
        ),
        migrations.AddField(
            model_name='studenttask',
            name='code_quality_score',
            field=models.FloatField(blank=True, default=0.0, help_text='Code quality & structure score (0-100)', null=True),
        ),
        migrations.AddField(
            model_name='studenttask',
            name='evaluated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studenttask',
            name='evaluated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluated_student_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studenttask',
            name='evaluation_status',
            field=models.CharField(choices=[('UNEVALUATED', 'Pending Evaluation'), ('EXCELLENT', 'Exceeded Expectations (A/A+)'), ('PASSED', 'Accepted / Passed'), ('NEEDS_REVISION', 'Needs Revision'), ('FAILED', 'Unsatisfactory / Re-do')], default='UNEVALUATED', max_length=30),
        ),
        migrations.AddField(
            model_name='studenttask',
            name='evaluator_feedback',
            field=models.TextField(blank=True, help_text='Comprehensive feedback and guidance from evaluator'),
        ),
        migrations.AddField(
            model_name='studenttask',
            name='grade',
            field=models.CharField(blank=True, choices=[('A+', 'A+ (Outstanding - 90-100)'), ('A', 'A (Excellent - 80-89)'), ('B+', 'B+ (Very Good - 70-79)'), ('B', 'B (Good - 60-69)'), ('C', 'C (Average - 50-59)'), ('NI', 'Needs Improvement (< 50)')], help_text='Grade: A+, A, B+, B, C, NI', max_length=10),
        ),
        migrations.AddField(
            model_name='studenttask',
            name='is_evaluated',
            field=models.BooleanField(default=False, help_text='Indicates whether this task has been evaluated'),
        ),
        migrations.AddField(
            model_name='studenttask',
            name='presentation_score',
            field=models.FloatField(blank=True, default=0.0, help_text='Presentation & documentation score (0-100)', null=True),
        ),
        migrations.AddField(
            model_name='studenttask',
            name='problem_solving_score',
            field=models.FloatField(blank=True, default=0.0, help_text='Problem solving & logic score (0-100)', null=True),
        ),
        migrations.AddField(
            model_name='studenttask',
            name='score',
            field=models.FloatField(blank=True, default=0.0, help_text='Overall task evaluation score (0-100)', null=True),
        ),
        migrations.AddField(
            model_name='studenttask',
            name='strengths',
            field=models.TextField(blank=True, help_text='Strengths observed in student execution'),
        ),
        migrations.AddField(
            model_name='studenttask',
            name='submission_notes',
            field=models.TextField(blank=True, help_text='Student submission description or explanation'),
        ),
        migrations.AddField(
            model_name='studenttask',
            name='submission_url',
            field=models.URLField(blank=True, help_text='GitHub repository, PR, or deliverable link'),
        ),
        migrations.AddField(
            model_name='studenttask',
            name='timeliness_score',
            field=models.FloatField(blank=True, default=0.0, help_text='Timeliness & promptness score (0-100)', null=True),
        ),
    ]
