# Generated by Django 5.2.17 on 2026-09-15 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator_app', '0006_studenttask_areas_for_improvement_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchScheduleException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_date', models.DateField(help_text='The date of the class that is being cancelled/shifted')),
                ('rescheduled_date', models.DateField(blank=True, help_text='The new date for the makeup class (leave blank if permanently cancelled)', null=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_exceptions', to='evaluator_app.batch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Batch Schedule Exception',
                'verbose_name_plural': 'Batch Schedule Exceptions',
                'unique_together': {('batch', 'original_date')},
            },
        ),
    ]
