# Generated by Django 5.2.17 on 2026-09-18 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator_app', '0007_batchscheduleexception'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyevaluation',
            name='project_and_practical_task_given',
            field=models.BooleanField(default=True, help_text='Did the student receive a project/practical task today?'),
        ),
        migrations.AddField(
            model_name='studenttask',
            name='document_upload',
            field=models.FileField(blank=True, help_text='Upload PPT/PDF/Word/Image (optional)', null=True, upload_to='student_tasks/documents/'),
        ),
    ]
