# Generated by Django 5.2.17 on 2026-09-18 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator_app', '0008_dailyevaluation_project_and_practical_task_given_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyevaluation',
            name='document_upload',
            field=models.FileField(blank=True, help_text='Upload PPT/PDF/Word/Image (optional)', null=True, upload_to='evaluations/documents/'),
        ),
    ]
