# Generated by Django 5.2.17 on 2026-09-21 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator_app', '0010_syllabus_batchsyllabus_syllabustask_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabus',
            name='total_modules',
            field=models.PositiveIntegerField(default=1, help_text='Total number of modules needed for this syllabus'),
        ),
    ]
