# Generated by Django 5.2.17 on 2026-09-21 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator_app', '0011_syllabus_total_modules'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syllabus',
            name='target_course',
        ),
    ]
