# Generated by Django 5.2.17 on 2026-09-22 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator_app', '0013_student_academic_year_student_student_class'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Thursday Combined CSE/AD', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batches', models.ManyToManyField(help_text='Select the batches to merge into this group', related_name='batch_groups', to='evaluator_app.batch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_batch_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Batch Group (Merged)',
                'verbose_name_plural': 'Batch Groups (Merged)',
                'ordering': ['-created_at'],
            },
        ),
    ]
