# Generated by Django 5.2.17 on 2026-09-22 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator_app', '0014_batchgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='payment_status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('UNPAID', 'Unpaid')], default='UNPAID', max_length=20),
        ),
    ]
