# Generated by Django 5.2.17 on 2026-09-22 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator_app', '0015_student_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabustask',
            name='default_assigner_name',
            field=models.CharField(blank=True, help_text='Name of unregistered assigner if applicable', max_length=255, null=True),
        ),
    ]
