# Generated by Django 5.2.17 on 2026-09-23 08:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator_app', '0016_syllabustask_default_assigner_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='end_time',
            field=models.TimeField(default=datetime.time(18, 0), help_text='Class ending time'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='start_time',
            field=models.TimeField(default=datetime.time(10, 0), help_text='Class starting time'),
        ),
    ]
