# Generated by Django 4.2.30 on 2026-09-29 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evaluator_app', '0017_alter_batch_end_time_alter_batch_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchtaskschedule',
            name='incharge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_task_schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='batchtaskschedule',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20),
        ),
    ]
