# Generated by Django 4.2.30 on 2026-09-29 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator_app', '0018_batchtaskschedule_incharge_batchtaskschedule_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttask',
            name='incharge_name',
            field=models.CharField(blank=True, help_text='Name of the person in charge (registered or unregistered)', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='studenttask',
            name='problem_document',
            field=models.FileField(blank=True, help_text='Upload problem statement (PDF, Word, etc.)', null=True, upload_to='student_tasks/problems/'),
        ),
    ]
