# Generated by Django 4.2.30 on 2026-09-29 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator_app', '0019_studenttask_incharge_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchtaskschedule',
            name='incharge_name',
            field=models.CharField(blank=True, help_text='For unregistered incharges', max_length=150),
        ),
    ]
