# Generated by Django 4.2.30 on 2026-09-29 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator_app', '0020_batchtaskschedule_incharge_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='batchtaskschedule',
            unique_together=set(),
        ),
    ]
